import { Injectable, inject } from '@angular/core'; import { HttpClient } from '@angular/common/http'; import { of, delay } from 'rxjs'; import { environment } from '../../environments/environment'; import { AppStore } from '../core/app.store'; import * as mock from './mock-data'; import { Project } from '../models/domain';
@Injectable({providedIn:'root'}) export class AuthService{ store=inject(AppStore); login(email:string){this.store.user.set({id:'u1',name:'Ava Architect',email,role:'Admin',organizationId:'o1'}); this.store.setToken('demo-jwt'); return of(true).pipe(delay(250));} register(email:string){return this.login(email)} logout(){this.store.user.set(null);this.store.setToken(null)} }
@Injectable({providedIn:'root'}) export class ProjectService{ http=inject(HttpClient); api=environment.apiUrl; list(){return of(mock.projects).pipe(delay(250))} get(id:string){return of(mock.projects.find(p=>p.id===id)??mock.projects[0]).pipe(delay(150))} create(p:Partial<Project>){return of({...mock.projects[0],...p,id:crypto.randomUUID(),completion:5,status:'Discovery'} as Project).pipe(delay(300))} }
@Injectable({providedIn:'root'}) export class DiscoveryService{ questions(){return of(mock.questions).pipe(delay(200))} saveDraft(){return of(true).pipe(delay(150))} }
@Injectable({providedIn:'root'}) export class ArchitectureModelService{ get(){return of(mock.model).pipe(delay(200))} generate(){return of({id:'job1',status:'running' as const,progress:42,categories:{model:70,artifacts:20,security:35},message:'Synthesizing target architecture'}).pipe(delay(400))} }
@Injectable({providedIn:'root'}) export class ArtifactService{ list(){return of(mock.artifacts).pipe(delay(200))} save(){return of(true).pipe(delay(150))} }
@Injectable({providedIn:'root'}) export class ExportService{ exportPackage(format:string){return of({url:'#',format}).pipe(delay(250))} }
@Injectable({providedIn:'root'}) export class OrganizationService{ get(){return of({id:'o1',name:'Contoso Architecture Office',industry:'Financial Services',plan:'Enterprise'}).pipe(delay(150))} }
@Injectable({providedIn:'root'}) export class UserService{ list(){return of([{id:'u1',name:'Ava Architect',email:'ava@contoso.com',role:'Admin',organizationId:'o1'}]).pipe(delay(150))} }
@Injectable({providedIn:'root'}) export class AuditLogService{ list(){return of(mock.logs).pipe(delay(150))} }
export { mock };
