import { ArchitectureModel, Artifact, AuditLog, CostEstimate, DiscoveryQuestion, Project, Risk, SecurityFinding } from '../models/domain';
export const risks:Risk[]=[{risk:'Legacy dependency incompatibility',category:'Migration',severity:'High',probability:'Medium',impact:'Release delay',mitigation:'Run compatibility assessment and strangler migration',owner:'Platform Lead',status:'Open'},{risk:'Data residency gap',category:'Compliance',severity:'Critical',probability:'Low',impact:'Regulatory breach',mitigation:'Pin resources to approved regions',owner:'Security',status:'Mitigating'}];
export const projects:Project[]=[{id:'p1',name:'.NET Framework to Azure Modernization',company:'Contoso',industry:'Financial Services',cloudProvider:'Azure',migrationType:'Application modernization',status:'Architecture generated',completion:78,lastUpdated:new Date().toISOString(),generatedArtifacts:12,openRisks:2,securityScore:86,estimatedMonthlyCost:18400,businessProblem:'Reduce datacenter dependency',currentArchitecture:'IIS, SQL Server, batch jobs',targetGoal:'Azure App Service, AKS, Azure SQL'}];
export const questions:DiscoveryQuestion[]=['Current state platforms and runtimes?','Target cloud landing zone?','Compliance obligations?','Availability and RTO/RPO?','Data classifications?','Integration patterns?','Budget guardrails?'].map((text,i)=>({id:`q${i+1}`,text,category:['Current','Target','Compliance','Operations','Data','Integration','Financial'][i],optional:i>4,answered:false}));
export const model:ArchitectureModel={businessContext:'Modernize core services while reducing operational risk.',currentState:'Monolithic .NET Framework apps hosted on IIS with SQL Server.',targetState:'Cloud-native Azure architecture using App Service, AKS, Azure SQL and managed identity.',applications:['Customer Portal','Admin API','Batch Processor'],integrations:['ERP via REST','Identity Provider via OIDC'],dataStores:['Azure SQL','Blob Storage','Key Vault'],infrastructure:['Hub-spoke network','Azure Firewall','Private Endpoints'],security:['Managed Identity','RBAC','Defender for Cloud'],deployment:['GitHub Actions','Blue/green releases'],operations:['Azure Monitor','Log Analytics','SLO dashboards'],assumptions:['Azure landing zone exists','Teams can adopt IaC'],constraints:['12 month timeline','PCI scope'],decisions:['Use managed PaaS first','Containerize long-running workers'],risks};
export const artifacts:Artifact[]=[{id:'a1',projectId:'p1',type:'ADR',name:'ADR-001 PaaS-first modernization',status:'Ready',language:'markdown',version:'v1',updatedAt:new Date().toISOString(),content:'# ADR-001 PaaS-first modernization\n\nUse Azure PaaS for web workloads.'},{id:'a2',projectId:'p1',type:'Terraform',name:'Azure baseline',status:'Draft',language:'terraform',version:'v2',updatedAt:new Date().toISOString(),content:'resource "azurerm_resource_group" "main" {\n  name = "rg-asa-prod"\n  location = "eastus"\n}'},{id:'a3',projectId:'p1',type:'Diagram',name:'Target architecture',status:'Ready',language:'mermaid',version:'v1',updatedAt:new Date().toISOString(),content:'flowchart LR\nUser-->FrontDoor-->AppService\nAppService-->AzureSQL\nAppService-->KeyVault'}];
export const findings:SecurityFinding[]=[{title:'Private endpoint coverage',area:'Network',severity:'Medium',recommendation:'Enable private endpoints for data services.'},{title:'Secrets in CI/CD',area:'Secrets',severity:'High',recommendation:'Use OIDC federation and Key Vault references.'}];
export const cost:CostEstimate={monthly:18400,yearly:220800,compute:7600,storage:900,database:5200,network:1300,monitoring:900,nonProduction:3400,production:15000,assumptions:['Reserved capacity not applied','East US pricing placeholder']};
export const logs:AuditLog[]=[{id:'l1',actor:'Ava Architect',action:'Generated architecture model',target:'p1',createdAt:new Date().toISOString(),ipAddress:'10.0.0.42'}];
